### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [linnnus/autovenv#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by linnnus** [comment]
I have added a license file to the repository, though I'm not sure if it's a good idea to add this project as it isn't very well-tested. It's just a small plugin I wrote for one of my friends. I don't even use it myself.

**Comment by unixorn** [comment]
If you don't think it's ready for public consumption, I'll leave it out. If you decide later that it's ready for release, either PR it into [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) or raise an issue there with a link to the repo and I'll add it for you.
